### ISSUE TITLE
Cannot create `hatchet.lock` without existing `hatchet.lock`

### ISSUE THREAD

**Issue by Malax** [heroku/hatchet#115]
`bundle exec hatchet lock` fails when there is no already existing `hatchet.lock`. Creating an empty `hatchet.lock` before executing `bundle exec hatchet lock` can be used as a workaround.

**Comment by schneems** [comment]
This is a duplicate of https://github.com/heroku/hatchet/issues/85, let's track it over there. What project did you run into this on?
