### ISSUE TITLE
Flappy test runs

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#120]
Here's an issue where we can track failures that shouldn't have happened so we can see if there's a recurring problem in Hatchet that can be updated.

List your component name and then a link to logs and the test failure for each incident of a flappy/failing CI run that should have not failed.

## Provider: Heroku CI

- Could not create test run. An unexpected error caused the job to fail.
  - https://dashboard.heroku.com/pipelines/ac057663-170b-4bdd-99d0-87560eb3a570/tests/1196?node=1

## Heroku Buildpack Ruby

- ~~Unhandled rate limit  => #127~~
- ~~403 Forbidden on delete pipeline => #129~~
- ~~Empty result from `app.run` => #131~~
- ~~Ruby version test fails~~ => https://github.com/heroku/heroku-buildpack-ruby/pull/1081
- ~~Chomp fails~~ => https://github.com/heroku/heroku-buildpack-ruby/pull/1085
- gnutls_handshake failed (github is throttling clones for `hatchet install` ?)
  - https://dashboard.heroku.com/pipelines/ac057663-170b-4bdd-99d0-87560eb3a570/tests/1175?node=1
- Heroku CI - Failed to initiate tests: Expected([201]) <=> Actual(503 Service Unavailable) 
  - https://dashboard.heroku.com/pipelines/ac057663-170b-4bdd-99d0-87560eb3a570/tests/1226
- `heroku run` executed against old slug ??
  - https://dashboard.heroku.com/pipelines/ac057663-170b-4bdd-99d0-87560eb3a570/tests/1528
  - When checking via `heroku run ruby -v -a hatchet-t-a9947d7f81` it outputs the correct values. My best guess is it's hitting something like https://github.com/heroku/hatchet/issues/116

## Hatchet

- Lock conflict  (Text file busy)
  - https://app.circleci.com/pipelines/github/heroku/hatchet/236/workflows/9aaa4538-6da8-4038-90c1-a2b74cf53ad9/jobs/691
- ~~CI looks fine but reporting failure => #137~~

## PHP

- "heroku-php-apache2: command not found" 
  - https://travis-ci.com/github/heroku/heroku-buildpack-php/jobs/389449034#L352
- Test run times out or hangs
  - https://travis-ci.com/github/heroku/heroku-buildpack-php/jobs/389848898

**Comment by edmorley** [comment]
## Python
* `Push failed: An unhandled error occurred` due to Codon's request to API timing out
  - Filed as https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008TzAHIA0/view
  - Codon's retry timeouts/logic has since been fixed to prevent this

**Comment by edmorley** [comment]
I just got failures like:

```
Retrying failed Attempt #1/3 to push for 'hatchet-t-ddbe2cb3b6' due to error: 
Hatchet::App::FailedDeployError Could not deploy 'hatchet-t-ddbe2cb3b6' (spec/fixtures/python_3.6_outdated) using 'Hatchet::GitApp' at path: 'spec/fixtures/python_3.6_outdated'
if this was expected add `allow_failure: true` to your deploy hash.
Buildpack: nil
Repo: https://git.heroku.com/hatchet-t-ddbe2cb3b6.git
output:
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> Building on the Heroku-20 stack        
remote: -----> Python app detected        
remote:  !     Python has released a security update! Please consider upgrading to python-3.6.12        
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes        
remote: -----> Installing python-3.6.11        
remote: -----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2        
remote: -----> Installing SQLite3        
remote: -----> Installing requirements with pip        
remote: -----> Discovering process types        
remote:        Procfile declares types -> (none)        
remote: 
remote: -----> Compressing...        
remote:        Done: 47.1M        
remote: -----> Launching...        
remote:        Released v3        
remote:        https://hatchet-t-ddbe2cb3b6.herokuapp.com/ deployed to Heroku        
remote: 
remote: 
remote: !	Heroku Git error, please try again shortly.        
remote: !	See http://status.heroku.com for current Heroku platform status.        
remote: !	If the problem persists, please open a ticket        
remote: !	on https://help.heroku.com/tickets/new        
remote: !	and provide the Request ID 687f8a07-24f4-4a19-be70-6aa8119ec924  
```

Checking request ID `687f8a07-24f4-4a19-be70-6aa8119ec924` in internal logs showed that the failure was due to exceeding the rate limit.

It looks like Endosome isn't handling this case gracefully, and as a result isn't outputting the rate limit error message, so Hatchet doesn't know to rate limit, and instead keeps on retrying, making the situation worse.

I'll file an internal ticket against Endosome.

**Comment by edmorley** [comment]
I got another failure from hitting the rate limit, where the rate limit was mentioned in the Git server response (unlike the above), but uses a different wording from the ones Hatchet recognises, causing Hatchet not to treat it as a rate limit error. 

I've filed #176 for that.

**Comment by edmorley** [comment]
I think this issue has run its course - since the most prevalent issues have since been fixed in Hatchet.

We're also prioritising libcnb-test moving forwards.
