### ISSUE TITLE
Warn when `buildpacks:` is specified but `:default` is not included

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#145]
I.e.

If you're using https://github.com/heroku/heroku-buildpack-jvm-common

And have this 

```
     Hatchet::Runner.new("java-getting-started", buildpacks: ["https://github.com/heroku/heroku-buildpack-java"]).tap do |app| 
```

We should warn that you're not testing against a branch by accident. However there are cases where one buildpack will use another buildpack. Like https://github.com/heroku/heroku-buildpack-jvm-common/blob/4c55cb39a08636f08d0b9aba10d592a63f969418/test/spec/java_spec.rb#L11 in those cases we can be more explicit by adding a branch like:

```
buildpacks: ["https://github.com/heroku/heroku-buildpack-java#main"],
```

**Comment by edmorley** [comment]
Wontfix given prioritising libcnb-test
