### ISSUE TITLE
Caching and output for CircleCI for repos

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#150]

**Comment by platipo** [comment]
Hi, I'm working for my [Orbtoberfest](https://hacktoberfest.circleci.com/) and I'd like to take this issue. Can you elaborate more on the title?

Also I noticed that the CircleCI config is still in version 2 and can be upgraded to 2.1 and implement Ruby orbs.

**Comment by edmorley** [comment]
We're not using Circle CI any more
