### ISSUE TITLE
Set multiple app env vars in one API call

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#160]
Currently if a Hatchet app is configured to have multiple env vars, Hatchet makes multiple calls to the Heroku platform API, setting one env var per call:
https://github.com/heroku/hatchet/blob/a3c728d9bbbdfae736d47f04885b292918162448/lib/hatchet/app.rb#L133-L136

However the platform API supports setting multiple env vars at once, which would help save test time and API rate limit usage:
https://devcenter.heroku.com/articles/platform-api-reference#config-vars-update

**Comment by schneems** [comment]
Seems good. 👍

**Comment by edmorley** [comment]
Wontfix given prioritising libcnb-test
