### ISSUE TITLE
`path_for_name` doesn't take into account hatchet.json directory config

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#161]
It's possible to override the default `REPOS_DIRECTORY_ROOT` of `"."` using:

```json
{
  "hatchet": {
    "directory": "custom/path"
  }
}
```

This is used by in most places, apart from `path_for_name`, which hardcodes `repos/` being in the project root:
https://github.com/heroku/hatchet/blob/97a18b873e9c0c5bcf3176a68b7b5ea79df77e5d/lib/hatchet/config.rb#L47

It seems this should instead be:

```ruby
      possible_paths = [repos[name.to_s], "#{repo_directory_path}/#{name}", name].compact
```

Or even better, it seems that the alternative style repo paths (presumably required for cases where there are multiple repos with the same short name) are added to `repos` itself by `init_config!`:
https://github.com/heroku/hatchet/blob/97a18b873e9c0c5bcf3176a68b7b5ea79df77e5d/lib/hatchet/config.rb#L71-L87

That way the affected line in `path_for_name` could be simplified to:

```ruby
      possible_paths = [repos[name.to_s], name].compact
```

...since the `repos` mapping would contain all of the variants itself.

**Comment by schneems** [comment]
Good catch
