### ISSUE TITLE
app.output includes stray trailing whitespace from Git

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#162]
In some new Hatchet tests, I wanted to assert that `app.output` contained an expected multi-line string.

For example:

```ruby
it 'fails the build' do
  app.deploy do |app|
    expect(app.output).to include(<<~OUTPUT)
      remote: -----> Python app detected
      remote:  !     Requested runtime (^3.9) is not available for this stack (#{app.stack}).
      remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
    OUTPUT
  end
end
```

However I found that the Hatchet `app.output` contained exactly 8 trailing spaces on all output lines:

```
remote: -----> Python app detected        \nremote:  !     Requested runtime (^3.9) is not available for this stack (heroku-18).        \n
```

After initially thinking these were added by Endosome, I tracked them down to Git itself:
https://github.com/git/git/blob/71ca53e8125e36efbda17293c50027d31681a41f/sideband.c#L116

For now I'm working around this via:

```ruby
def clean_output(output)
  output.gsub(/ {8}(?=\R)/, '')
end
```

And then:

```ruby
expect(clean_output(app.output)).to include(<<~OUTPUT)
  ...
OUTPUT
```

However it would be great if Hatchet removed this trailing whitespace from the Git output itself.

**Comment by schneems** [comment]
> However it would be great if Hatchet removed this trailing whitespace from the Git output itself.

You can use `app.output.strip` or `app.output.chomp`. Strip removes multiple whitespace and can handle a double newline (which sometimes `heroku run` returns) so it's what I use. Chomp wouldn't handle repeated whitespace.

Ahh, okay. I actually understand the issue. Strip can't fix this. You need a per-line strip for trailing whitespace, but not the newline.

I don't have any multiline matches in my tests. I would prefer to do this as two different includes assertions.

In this case we just want to know whether or not a specific output was triggered. Tightly coupling the exact output to the behavior assertion doesn't buy us much.

If you feel strongly about keeping the multi-line insertion I think it's probably fine to strip all of the output lines. Ultimately I don't love the multi-line assertion use case, but I do think the trailing spaces at the end is confusing. I'm 👍 on removing them.
