### ISSUE TITLE
Instance variable not initialized warnings

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#164]
When running Hatchet tests with rspec's `config.warnings = true`, there are a number of warnings generated by Hatchet like:

```
lib/hatchet/app.rb:360: warning: instance variable @run_multi_is_setup not initialized
lib/hatchet/git_app.rb:36: warning: instance variable @buildpack not initialized
```

This is using Hatchet 7.3.3 on Ruby 2.7.2.

**Comment by schneems** [comment]
This warning is going away from Ruby 3.0 fwiw. It's determined to not be that helpful and removing it gives a perf bump.

**Comment by schneems** [comment]
https://github.com/ruby/ruby/pull/3879#issuecomment-749918973
