### ISSUE TITLE
Provide helper method for updating buildpacks (App.update_buildpacks)

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#166]
There are a number of scenarios where it is useful to be able to perform a build using one set of buildpacks, then build the same app again with a different set of buildpacks. For example testing whether a buildpack can successfully read the cache data written by an older version of the buildpack.

Currently to update the buildpacks, one has to use `app.api_rate_limit.call.buildpack_installation.update()` - for example:

```ruby
context 'when no Python version is specified' do
  let(:buildpacks) { [:default] }
  let(:app) { new_app('spec/fixtures/python_version_unspecified', buildpacks: buildpacks) }

  context 'with a new app' do
    # ...
  end

  context 'with an app last built using an older default Python version' do
    let(:buildpacks) { ['https://github.com/heroku/heroku-buildpack-python#v171'] }

    it 'builds with the same Python version as the last build' do
      app.deploy do |app|
        # Build again, but with the current buildpack version
        buildpacks = [{buildpack: Hatchet::App.default_buildpack}]
        app.api_rate_limit.call.buildpack_installation.update(app.name, updates: buildpacks)
        app.commit!
        app.push!
        # ...
      end
    end
  end
end
```

It would be great to have a simpler API available, which:
* is on the app object (eg `app.update_buildpacks` for parity with `app.update_stack`)
* accepts a flat list, saving the need to create the list of hashes with a single property
* for bonus points, accepts the `:default` buildpack identifier, like the `buildpacks` argument to `App.new` does

In the meantime I'm using this in `spec_helper.rb`:

```ruby
def update_buildpacks(app, buildpacks)
  buildpack_list = buildpacks.map { |b| { buildpack: (b == :default ? app.class.default_buildpack : b) } }
  app.api_rate_limit.call.buildpack_installation.update(app.name, updates: buildpack_list)
end
```

**Comment by schneems** [comment]
I'm 👍 on adding a `update_buildpacks` command.

**Comment by edmorley** [comment]
Wontfix given prioritising libcnb-test
