### ISSUE TITLE
Show output of subcommands run by hatchet ci:setup

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#168]
The `hatchet ci:setup` command runs this script:
https://github.com/heroku/hatchet/blob/main/etc/ci_setup.rb

Which itself calls `hatchet ci:heroku_install` and `hatchet install`:
https://github.com/heroku/hatchet/blob/97a18b873e9c0c5bcf3176a68b7b5ea79df77e5d/etc/ci_setup.rb#L29-L30

However the stdout of those two commands isn't shown, meaning that this output isn't:
https://github.com/heroku/hatchet/blob/97a18b873e9c0c5bcf3176a68b7b5ea79df77e5d/bin/hatchet#L28-L32

This means it's not possible to tell whether `hatchet ci:setup` is also installing the Heroku CLI as well.

For example recently @dzuelke discovered that the CLI that was installed earlier in the Travis run was not on path, causing `hatchet ci:setup` to install a second copy.

Being able to see ```installing `heroku` command``` vs ```The `heroku` command is already installed``` would make this easier to debug.

**Comment by schneems** [comment]
👍 let's fix it. I think stdout is getting swallowed somewhere, I'm not totally sure where though.

**Comment by edmorley** [comment]
Wontfix given prioritising libcnb-test
