### ISSUE TITLE
Support Circle CI environment variables in Hatchet.git_branch

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#179]
Currently `Hatchet.git_branch` only recognises Travis CI environment variables, and for Circle CI has to fall back to querying Git:
https://github.com/heroku/hatchet/blob/f97e6f587ed489a1c9e6d4ee907375f9599d74e7/lib/hatchet.rb#L28-L38

Circle sets the `CIRCLE_BRANCH` environment variable that could be used instead:
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by schneems** [comment]
I think the original reason for the travis code was that it stripped the git repo or branch info maybe? Not shelling out will be a tiny perf benefit. I'm not sure if there's other benefits.

**Comment by edmorley** [comment]
> I'm not sure if there's other benefits.

It avoids #180, though it's likely worth fixing that anyway for local use-cases.
