### ISSUE TITLE
The return value of Hatchet::App.default_buildpack changes during the test run

### ISSUE THREAD

**Issue by edmorley** [heroku/hatchet#180]
In one of the Python buildpack's tests, I use call `Hatchet::App.default_buildpack` during the test itself:

```ruby
  context 'when there are no recognised Python project files' do
    let(:app) { new_app('spec/fixtures/no_python_project_files', allow_failure: true) }

    it 'fails detection' do
      app.deploy do |app|
        expect(clean_output(app.output)).to include(<<~OUTPUT)
          remote: -----> App not compatible with buildpack: #{Hatchet::App.default_buildpack}
          remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
        OUTPUT
      end
    end
  end
```

On Travis this works fine, but on Circle CI I get:

Expected...
`remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-python.git#master`

Actual:
`remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-python.git#circleci-setup`

I'm pretty sure this is because:
* on Circle CI, `Hatchet.git_branch` doesn't know about Circle's branch env vars, so has to fall back to shelling out to Git (see #179)
* this is fine at `Hatchet.App` instantiation (when `Hatchet::App.default_buildpack` is called to set the current app's buildpack) since the working directory is still the buildpack
* however `Hatchet::App.default_buildpack` doesn't memoize the result, so later when called again during the test, it has to call `Hatchet.git_branch` again, at which point the current working directory is actually for the test fixture, not the buildpack - so `git rev-parse --abbrev-ref HEAD` gives the fixture's branch name instead

It seems the fix here is to do any/all of:
* memoize `Hatchet::App.default_buildpack`
* make `Hatchet.git_branch` specify an explicit directory of the current project before shelling out to Git
* fix #179

**Comment by edmorley** [comment]
This also affects my tests that change buildpack partway through (ref #166), eg:
https://github.com/heroku/heroku-buildpack-python/blob/f4d3afe0ff6b4577ee69131bc3b4b26261ddbe93/spec/hatchet/python_version_spec.rb#L59-L73

**Comment by schneems** [comment]
## Sidenote

The test could be less specific:

```ruby
expect(clean_output(app.output)).to include("remote: -----> App not compatible with buildpack:")
```

Would still work in this case. Or even `remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-python#` (without the branch name).

## This issue

I didn't intend/expect for `default_buildpack` to be run inside of an test fixture app dir. I think memorizing that is also good for performance, and will make it behave better.

 #179 as a fix is fine too, though playing wack-a-mole with all the different CI providers. So if we fix #179 then I think we should also add memorization. Could you send a PR?

**Comment by edmorley** [comment]
> The test could be less specific:

Ah so that test is testing both lines for a specific reason - if the buildpack's `bin/detect` provided useful help, it would appear between those two lines. In the future I'm going to add that to `bin/detect`, at which point the content would go between the two. The test was my way of documenting how unhelpful the current buildpack UX was for the user. For now I've updated that test to use a multi-line regex, which passes.

That test was also perhaps not the best example to give for this issue - I have another which uses `default_buildpack`, but as part of changing the buildpacks set on an app to test forwards-backwards compat:
https://github.com/heroku/heroku-buildpack-python/blob/f4d3afe0ff6b4577ee69131bc3b4b26261ddbe93/spec/hatchet/python_version_spec.rb#L59-L73

> Could you send a PR?

Yeah happy to -- though was wondering how the usual memoization trick of using an instance attribute and `||=` worked with a class method?

**Comment by schneems** [comment]
> though was wondering how the usual memoization trick of using an instance attribute and ||= worked with a class method?

You can do it two ways. You can use a "class instance variable" with `@@myval ||= <calculate>` or alternatively you can specify an instance variable on the class.

```ruby
def self.default_buildpack
  @@default_buildpack ||= private_default_buildpack
end
```

or 

```ruby
@default_buildpack = nil
def self.default_buildpack
  @default_buildpack ||= private_default_buildpack
end
```

The `@@default_buildpack` has some properties that some people feel are confusing. It's accessible by both the class AND instances. It makes it a very not-threadsafe variable if instances ever need to mutate the value. The `@default_buildpack` at the class level is "safer" as the instance cannot access it.

**Comment by edmorley** [comment]
Hmm so unfortunately #183 didn't fully resolve this, as seen by the failure in:
https://app.circleci.com/pipelines/github/heroku/heroku-buildpack-python/57/workflows/0a2385be-e5c2-41d5-a90e-7b02ff9cf0b0/jobs/205

For this test:

```ruby
  context 'when no Python version is specified' do
    let(:buildpacks) { [:default] }
    let(:app) { Hatchet::Runner.new('spec/fixtures/python_version_unspecified', buildpacks: buildpacks) }

    # (other tests removed)

    context 'with an app last built using an older default Python version' do
      # This test performs an initial build using an older buildpack version, followed
      # by a build using the current version. This ensures that the current buildpack
      # can successfully read the version metadata written to the build cache in the past.
      let(:buildpacks) { ['https://github.com/heroku/heroku-buildpack-python#v189'] }

      it 'builds with the same Python version as the last build' do
        app.deploy do |app|
          update_buildpacks(app, [:default])
          app.commit!
          app.push!
          expect(clean_output(app.output)).to include(<<~OUTPUT)
            remote: -----> Python app detected
            remote:  !     Python has released a security update! Please consider upgrading to python-#{LATEST_PYTHON_3_6}
            remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
          OUTPUT
          expect(app.run('python -V')).to include('Python 3.6.12')
        end
      end
    end
  end
```

In the above test, the original `Hatchet::Runner.new()` call specified a custom buildpacks list that didn't include `:default`, so `Hatchet::App.default_buildpack` never got invoked prior to the initial `deploy`. Therefore the fix of memoizing doesn't help, as the first time it's called, the working directory has already changed.

I believe the real fix for this issue would be to ensure the correct working directory is specified explicitly here:
https://github.com/heroku/hatchet/blob/d737fe02fffe3ef559551c1da5685c7b7f258792/lib/hatchet.rb#L28-L38

**Comment by edmorley** [comment]
Wontfix given prioritising libcnb-test
