### ISSUE TITLE
Needs an anvil host?

### ISSUE THREAD

**Issue by pjaspers** [heroku/hatchet#32]
I was trying to use this to test a very simple buildpack.

Since I wanted to test this before pushing to Github, I should use the Anvil workflow, but `anvil-cli` wants to talk to `api.anvilworks.org` which is no longer a functioning thing. So is there some flag that I should set?

I was looking at the `heroku-buildpack-ruby` but that doesn't have a `ANVIL_HOST` set in it either.

Any pointers?

**Comment by schneems** [comment]
We always use Hatchet::Runner which defaults to git. So you have to push the code you're testing to github, but it works and it is reliable. Anvil went away, we should probably deprecate it and remove from hatchet.
