### ISSUE TITLE
More descriptive logging

### ISSUE THREAD

**Issue by Malax** [heroku/hatchet#87]
It would be nice to have the test name in this output too:

`.Hatchet setup: "htcht-359335657-5d891c21f5" for "java-servlets-sample"`

Similar issue for retries:

`RSpec::Retry: 2nd try ./test/spec/java_spec.rb:82`

**Comment by schneems** [comment]
I worked backwards instead. When a test fails it includes the app name and repo name https://github.com/heroku/hatchet/pull/136

For this one:

> RSpec::Retry: 2nd try ./test/spec/java_spec.rb:82

That would require an upstream pr to Rspec::Retry. I think I would want to ouput the full failure and not just say "why" it's being retried.

**Comment by edmorley** [comment]
Wontfix given prioritising libcnb-test
